---
- hosts: all
  gather_facts: no
  strategy: free
  user: ubuntu
  tasks:
   - name:
     ansible.builtin.wait_for_connection:
   - name: Copy multuclusterkind directory
     copy:
       src: "{{ item }}"
       dest: /home/ubuntu/
       owner: ubuntu
       group: ubuntu
       mode: 0644
     loop:
       - ./scripts/multiclusterkind
       - /home/workshop/nephio-test-github-pat.txt
   - name: Post-provision VM process
     command: "bash /home/ubuntu/multiclusterkind/{{ item }}"
     loop:
       - k8s_cluster_setup.sh
       - kind_create_clusters.sh 4
       - configure.sh
