apiVersion: config.porch.kpt.dev/v1alpha1
kind: Repository
metadata:
  name: catalog
  namespace: default
spec:
  content: Package
  deployment: false
  git:
    branch: main
    createBranch: true
    directory: /
    repo: https://github.com/nephio-test/participant-catalog.git
    secretRef:
      name: github-personal-access-token
  type: git
